query AnimeDetailsQuery($id: String!) {
    animes(ids: $id) {
        id
        name
        russian
        english
        japanese
        synonyms
        licenseNameRu
        poster { ...PosterFragment }
        kind
        score
        status
        rating
        episodes
        episodesAired
        duration
        airedOn { ...IncompleteDateFragment }
        releasedOn { ...IncompleteDateFragment }
        season
        descriptionHtml
        descriptionSource
        genres {
            id
            name
            russian
            kind
        }
        nextEpisodeAt
        fansubbers
        fandubbers
        scoresStats {
            score
            count
        }
        statusesStats {
            status
            count
        }
        studios {
            id
            name
            imageUrl
        }
        related {
            anime { ...AnimeFragment }
            manga { ...MangaFragment }
            relationKind
        }
        screenshots {
            x332Url
            x166Url
            originalUrl
        }
        videos {
            url
            imageUrl
            playerUrl
            kind
            name
        }
    }
}