query AnimeQuery(
    $page: Int
    $limit: Int
    $order: OrderEnum
    $kind: AnimeKindString
    $status: AnimeStatusString
    $season: SeasonString
    $score: Int
    $duration: DurationString
    $rating: RatingString
    $genre: String
    $studio: String
    $franchise: String
    $censored: Boolean
    $mylist: MylistString
    $ids: String
    $excludeIds: String
    $search: String
) {
    animes(
        page: $page
        limit: $limit
        order: $order
        kind: $kind
        status: $status
        season: $season
        score: $score
        duration: $duration
        rating: $rating
        genre: $genre
        studio: $studio
        franchise: $franchise
        censored: $censored
        mylist: $mylist
        ids: $ids
        excludeIds: $excludeIds
        search: $search
    ) {
        id
        name
        russian
        poster { originalUrl previewUrl }
        kind
        score
        status
        episodes
        episodesAired
        airedOn { day month year }
        releasedOn { day month year }
        userRate {
            id
            createdAt
            updatedAt
            status
            score
            episodes
            chapters
            volumes
            rewatches
            text
        }
    }
}