query MangaUserRatesQuery(
    $page: PositiveInt!
    $limit: PositiveInt!
    $status: UserRateStatusEnum!
    $orderInput: UserRateOrderInputType!
    $userId: ID
) {
    userRates(
        page: $page
        limit: $limit
        status: $status
        targetType: Manga
        userId: $userId
        order: $orderInput
    ) {
        id
        createdAt
        updatedAt
        status
        score
        chapters
        volumes
        rewatches
        text
        manga {
            id
            name
            russian
            poster {
                originalUrl
                main2xUrl
            }
            kind
            score
            status
            chapters
            volumes
            airedOn {
                day
                month
                year
            }
            releasedOn {
                day
                month
                year
            }
        }
    }
}