package ru.vladsaybulin.model

class AnimeDetails(
    val id: Long,
    val originalName: String,
    val russianName: String?,
    val englishName: String?,
    val japaneseName: String?,
    val alternativeName: List<String>,
    val licenseNameRu: String?,
    val poster: Poster?,
    val kind: AnimeKind,
    val score: Float?,
    val status: EntryStatus,
    val rating: AnimeRating,
    val episodes: Int,
    val episodesAired: Int,
    val duration: Int?,
    val airedOn: IncompleteDate?,
    val releasedOn: IncompleteDate?,
    val descriptionBBCode: String?,
    val descriptionSource: String?,
    val genres: List<Genre>?,
    val subbers: List<String>?,
    val dubbers: List<String>?,
    val scoreStats: List<Statistic<Int>>?,
    val userRateStatusStats: List<Statistic<UserRateStatus>>?,
    val studios: List<Studio>?,
    val authors: List<PersonWithRoles>?,
    val characters: List<CharacterWithRole>?,
    val relations: List<RelatedEntry>?,
    val screenshots: List<Screenshot>,
    val videos: List<Video>?
)